<?php
require_once __DIR__ . '/../security.php';
requireAdmin();

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    header('HTTP/1.1 405 Method Not Allowed');
    exit;
}

$tables = ['settings', 'users', 'mangas', 'chapters', 'receipts', 'purchases'];
$sqlDump = "-- Mangata DB Backup\n-- Date: " . date("Y-m-d H:i:s") . "\n-- This file is auto-generated by Mangata secure backup engine.\n\n";

foreach ($tables as $table) {
    $stmt = $pdo->query("SELECT * FROM `$table`");
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    if (count($rows) > 0) {
        $sqlDump .= "-- Table: $table\n";
        $sqlDump .= "TRUNCATE TABLE `$table`;\n";
        
        foreach ($rows as $row) {
            $keys = array_keys($row);
            $values = array_map(function($val) use ($pdo) {
                if ($val === null) return 'NULL';
                return $pdo->quote($val); // Securely escape value to avoid Injection on restore
            }, array_values($row));
            
            $sqlDump .= "INSERT INTO `$table` (`" . implode("`, `", $keys) . "`) VALUES (" . implode(", ", $values) . ");\n";
        }
        $sqlDump .= "\n";
    }
}

// Ensure error reporting doesn't output into our SQL script
if (ob_get_length()) ob_clean();

header('Content-Type: application/sql');
header('Content-Disposition: attachment; filename="mangata_backup_' . date("Y_m_d_H_i") . '.sql"');
header('Cache-Control: max-age=0');
echo $sqlDump;
exit;
